// ForecastTemp.cpp
#include "ForecastTemp.h"
#include "Common.h"
#include <string>

ForecastData currentData;
std::deque<ForecastData> forecastedData;

void setupWeatherApi()
{
    String subscriptionName = String::format("%s/%s/", System.deviceID().c_str(), WEATHER_EVENT_NAME); // {{{PARTICLE_DEVICE_ID}}}/{{{PARTICLE_EVENT_NAME}}}
    Particle.subscribe(subscriptionName, subscriptionHandler, MY_DEVICES);
    Log.info("Subscribing to event %s", subscriptionName.c_str());
}

void requestWeatherData()
{
    if (Particle.connected())
    {
        Log.info("Requesting event (%s) data", WEATHER_EVENT_NAME);
        Particle.publish(WEATHER_EVENT_NAME, "", PRIVATE);
    }
}

// Function to decode the data. Generated by https://docs.particle.io/integrations/webhook-demo/
// Format is the following:
//  {"current": {"dt":{{current.dt}}, "temp":{{current.temp}}},
// "hourly":[{"dt":{{hourly.0.dt}},"temp":{{hourly.0.temp}}},
// {"dt":{{hourly.1.dt}},"temp":{{hourly.1.temp}}},
// {"dt":{{hourly.2.dt}},"temp":{{hourly.2.temp}}}]}
void subscriptionHandler(const char *event, const char *data)
{
    JSONValue outerObj = JSONValue::parseCopy(data);
    JSONObjectIterator iter(outerObj);

    Log.info("Event (%s) data received", WEATHER_EVENT_NAME);

    while (iter.next())
    {
        if (iter.name() == "current")
        {
            JSONObjectIterator iter2(iter.value());
            while (iter2.next())
            {
                if (iter2.name() == "dt")
                {
                    currentData.timestamp = iter2.value().toInt();
                }
                if (iter2.name() == "temp")
                {
                    currentData.temperature = iter2.value().toDouble();
                }
            }
        }
        if (iter.name() == "hourly")
        {
            JSONArrayIterator iter2(iter.value());
            for (size_t ii = 0; iter2.next(); ii++)
            {
                JSONObjectIterator iter3(iter2.value());
                while (iter3.next())
                {
                    if (iter3.name() == "dt")
                    {
                        forecastedData[ii].timestamp = iter3.value().toInt();
                    }
                    if (iter3.name() == "temp")
                    {
                        forecastedData[ii].temperature = iter3.value().toDouble();
                    }
                }
            }
        }
    }

    printWeatherData(); // Pretty print the received weather data
}

void printWeatherData()
{
    Log.info("Weather forecast, currentTime: %ld, currentTemp %lf C", currentData.timestamp, currentData.temperature); // Print the weather API data to the serial monitor
    for (unsigned int i = 0; i < forecastedData.size(); i++)
    {
        Log.info("Weather forecast, hour %d Time: %ld, hour %d Temp %lf C", i + 1, forecastedData[i].timestamp, i + 1, forecastedData[i].temperature); // Print the weather API data to the serial monitor
    }
}
